{
 "title": "Micrometer Hystrix (CF)",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "cf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "App Name",
    "query": "label_values(system_cpu_count, app_name)"
   },
   {
    "name": "cf_instance_id",
    "label": "CF Instance Id",
    "query": "label_values(system_cpu_count{app_name =\"$app_name\"}, cf_instance_id)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(hystrix_execution_total{app_name=\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}, group)"
   },
   {
    "name": "key",
    "label": "Key",
    "query": "label_values(hystrix_execution_total{app_name =\"$app_name\", cf_instance_id=~\"$cf_instance_id\", group=~\"$group\"}, key)"
   }
  ]
 },
 "panels": [
  { "title": "Open Circuit Breaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count of open circuit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hystrix_circuit_breaker_open{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"})"
    }
   ]
  },
  {
   "title": "Open Circuit Breaker",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "Hystrix Execution ( / s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Success Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"success\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Emit Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"emit\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "ShortCircuited Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"short_circuited\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "BadRequest Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"bad_request\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Failure Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"failure\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Timeout Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"timeout\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "SemaphoreRejected Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"semaphore_rejected\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "ThreadPoolRejected Event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"thread_pool_rejected\"}[120s])) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"failure\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Timeout Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"timeout\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "ShortCircuited Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"short_circuited\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "BadRequest Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"bad_request\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "SemaphoreRejected Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"semaphore_rejected\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "ThreadPoolRejected Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hystrix_execution_total{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\", event=\"thread_pool_rejected\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  { "title": "Hystrix Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latency Execution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(hystrix_latency_execution_seconds{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}) by (app_name, cf_instance_id, group, key)",
     "legendFormat": "{{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Latency Execution Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hystrix_latency_execution_seconds_bucket{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}[5m])) by (app_name, cf_instance_id, group, key, le))",
     "legendFormat": "50p - {{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(hystrix_latency_execution_seconds_bucket{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}[5m])) by (app_name, cf_instance_id, group, key, le))",
     "legendFormat": "90p - {{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hystrix_latency_execution_seconds_bucket{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}[5m])) by (app_name, cf_instance_id, group, key, le))",
     "legendFormat": "95p - {{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(hystrix_latency_execution_seconds_bucket{app_name=~\"$app_name\",cf_instance_id=~\"$cf_instance_id\", group=~\"$group\", key=~\"$key\"}[5m])) by (app_name, cf_instance_id, group, key, le))",
     "legendFormat": "99p - {{group}}/{{key}} - {{app_name}}/{{cf_instance_id}}"
    }
   ]
  }
 ]
}