{
 "title": "Micrometer Summary (CF)",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer",
  "cf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "space_name",
    "label": "Space Name",
    "query": "label_values(system_cpu_count, space_name)"
   },
   {
    "name": "app_name",
    "label": "App Name",
    "query": "label_values(system_cpu_count{space_name=~\"$space_name\"}, app_name)"
   },
   {
    "name": "cf_instance_id",
    "label": "App Instance ID",
    "query": "label_values(system_cpu_count{app_name=\"$app_name\", space_name=~\"$space_name\"}, cf_instance_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Uptime (Min)",
     "type": "singlestat",
     "description": "The uptime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(process_uptime_seconds{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"})"
      }
     ]
    },
    {
     "title": "Process Start Time (Min)",
     "type": "singlestat",
     "description": "The starttime of the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "(time() - min(process_uptime_seconds{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"})) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor Count (Max)",
     "type": "singlestat",
     "description": "The number of processors available to the Java virtual machine",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(system_cpu_count{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{space_name=~\"$space_name\", app_name=~\"$app_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "CPU Load Average",
     "type": "graph",
     "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trace log event",
     "type": "graph",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\", level=\"trace\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Debug log event",
     "type": "graph",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\", level=\"debug\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Info log event",
     "type": "graph",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\", level=\"info\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Warn log event",
     "type": "graph",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\", level=\"warn\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Error log event",
     "type": "graph",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\", level=\"error\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Peak",
     "type": "graph",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Live Daemon Threads",
     "type": "graph",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Live Total Threads",
     "type": "graph",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DBCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Idle Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_idle{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Min/Max Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_max{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "max/{{app_name}}/{{cf_instance_id}}"
      },
      {
       "expr": "hikaricp_connections_min{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "min/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}}/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{id}} ({{area}})/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Data Size",
     "type": "graph",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Promoted Total",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_memory_promoted_bytes_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Allocation Total",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_memory_allocated_bytes_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Pause Count",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{cause}} ({{action}})/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Pause Duration Rate",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}[5m])",
       "legendFormat": "{{cause}} ({{action}})/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Class Loader Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_unloaded_total{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Rate",
     "type": "graph",
     "description": "Count of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}[120s])",
       "legendFormat": "{{method}} {{uri}} - {{status}}/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    },
    {
     "title": "Max HTTP Requests Time",
     "type": "graph",
     "description": "Timer of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
       "legendFormat": "{{method}} {{uri}} - {{status}}/{{app_name}}/{{cf_instance_id}}"
      }
     ]
    }
   ]
  },
  { "title": "MQ Listener Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MQ Listener Rate",
   "type": "graph",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}[120s])",
     "legendFormat": "{{name}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  },
  {
   "title": "Max MQ Listener Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_integration_send_seconds_max{app_name=~\"$app_name\", space_name=~\"$space_name\", cf_instance_id=~\"$cf_instance_id\"}",
     "legendFormat": "{{name}}/{{app_name}}/{{cf_instance_id}}"
    }
   ]
  }
 ]
}